# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f930486c183a7cd26f233250f532b73e2c30b72efb045f82d8674dc820a2f117b2761327e0b6d5353588e79c0f3879524943b40afc52aa2d64284873ab08e4

test:
  secret_key_base: 859e2c70e614c4f3daf93d478d7eea95c674919199a326edbb135523467cd27ec90f548590d72f8efcdf2889ce4b4c0b49e790a29c6f521c03a5475037633837

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
